### ISSUE TITLE
Support warning/error messages

### ISSUE THREAD

**Issue by evant** [Foso/MpApt#8]
A java annotation processor can report warnings/errors with `javax.annotation.processing.Messager` which can include a message as well as what element that message is on. Would be nice to have a similar api available. You seem to have a `log()` method on `AbstractProcessor()` but it seems pretty limited.

**Comment by Foso** [comment]
Hi, i haven't documented it yet. But i wrote an extension method MessageCollector.printMessage(diagnosticKind: DiagnosticKind, message: String)
(in https://github.com/Foso/MpApt/blob/master/mpapt-runtime/src/main/java/de/jensklingenberg/mpapt/utils/KaptUtils.kt) 
 to try to provide a similar api to the java annotation processor. 

You can get the MessageCollector from the configuration like this:
```kotlin
val messager = configuration.get(CLIConfigurationKeys.MESSAGE_COLLECTOR_KEY,MessageCollector.NONE)
messager.printMessage(DiagnosticKind.ERROR,"My error message")

```


I will add it to the documentation

**Comment by evant** [comment]
👍 any plan to add an argument to pass the element the warning/error happened on?

**Comment by Foso** [comment]
I hadn't considered this before, but i took a quick look how can be done with compiler api. I changed the printMessage() and added the CompilerMessageLocation as a parameter. 

Inside your processor, you can use it like that: 
```kotlin
configuration.messager().printMessage(DiagnosticKind.ERROR,"My error message", CompilerMessageLocation.Companion.create("/home/jens/Code/2019/MpApt/kotlin-plugin-shared/src/main/java/de/jensklingenberg/MpAptTestProcessor.kt",42,106))
```

This will print the message to the log and stop the compiler:
```kotlin
e: /home/jens/Code/2019/MpApt/kotlin-plugin-shared/src/main/java/de/jensklingenberg/MpAptTestProcessor.kt: (42, 106): My error message

```

I can't add an element parameter yet, because my element type doesn't have the (line,column)-Information. But i think it could be possible to get information out of a "descriptor"
